version: '2'

services:
  app:
    image: 'docker-test:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/hanaroholdings?autoReconnect=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=goodman
      - SPRING_DATASOURCE_PASSWORD=Gmc@1234!
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres